### ISSUE TITLE
Fatal error importing content - isDraft is not a function

### ISSUE THREAD

**Issue by andrewrutter** [contentful/contentful-import#10]
I am trying to import content which was exported using the contentful-export cli tool. I am getting the following error which is killing the import process:

```
ERR! TypeError: entry.isDraft is not a function 
ERR! Failed within
 TypeError: entry.isDraft is not a function
ERR! Failed within
     at /usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/push/push-to-space.js:116:22
ERR! Failed within
     at Array.filter (native)
ERR! Failed within
     at /usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/push/push-to-space.js:114:42
ERR! Failed within
     at run (/usr/local/lib/node_modules/contentful-import/node_modules/core-js/library/modules/es6.promise.js:87:22)
ERR! Failed within
     at /usr/local/lib/node_modules/contentful-import/node_modules/core-js/library/modules/es6.promise.js:100:28
ERR! Failed within
     at flush (/usr/local/lib/node_modules/contentful-import/node_modules/core-js/library/modules/_microtask.js:18:9)
ERR! Failed within
     at doNTCallback0 (node.js:407:9)
ERR! Failed within
     at process._tickCallback (node.js:336:13)
ERR! Failed within
  [TypeError: entry.isDraft is not a function]
```

The export was generated with just the --download-assets switch do I need to specify any other options when generating the export?

**Comment by Khaledgarbaya** [comment]
Hi @andrewrutter, which version do you use ?

**Comment by andrewrutter** [comment]
2.2.0 I installed it cleanly this morning

Export is showing as version 2.3.0

Thanks,

Andrew Rutter
President
Creative Clarity Inc.

andrew@creativeclaritycreations.com | 404.372.7430 | @clearcreativity

**Comment by Khaledgarbaya** [comment]
@andrewrutter I pushed a fix to the batch-libs that will prevent this error. if you update the contentful-import, the batch libs version should be 4.8.1

**Comment by andrewrutter** [comment]
Still seeing batch-libs as 4.7.4. I uninstalled and reinstalled completely but no difference

**Comment by Khaledgarbaya** [comment]
ok I bumped the version in contentful-import, a new version should be out in few minutes

**Comment by axe312ger** [comment]
@andrewrutter could you solve the issue? :)

**Comment by axe312ger** [comment]
Ohh, actually that was fixed in the latest version. Please upgrade your local version and open a new issue in case this problem still occurs.
