### ISSUE TITLE
Allow import of invalid entries

### ISSUE THREAD

**Issue by ChaosSteffen** [contentful/contentful-import#102]
We use this tool as part of a backup and restore workflow. From time to time it can happen that a space contains entries that do not match their validations anymore, because those where changed afterwards.

In this case I can still export the space but not import these entries. Which defeats the purpose of a backup script.

I see two solutions to this:
1) Provide an interface that allows to detect and repair invalid entries
2) Allow to import invalid entries for the sake of restoring data

I would love to see this solved somehow.

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
