### ISSUE TITLE
Is '--no-update' or 'noUpdate' option supported?

### ISSUE THREAD

**Issue by shailender-bathula** [contentful/contentful-import#118]
From the code the `pushToSpace` function doesn't seem to support `noUpdate` option.

Any timeline on when support for that would be implemented?

Creating a issue here, since `contentful-cli` is using this library for import.

Thanks.

**Comment by Rikusor** [comment]
Any updates for this? Would also need this information.

**Comment by chardcyber** [comment]
I can confirm this is a bug. will this be fixed anytime soon?

**Comment by phoebeschmidt** [comment]
Hi unfortunately we haven't had a chance to fix this yet. In the meantime PRs are always welcome :)

**Comment by anthonyjbarnes** [comment]
To be honest its not a bug. It looks more like an idea or feature that was intended but never added. as there is no code related to `--no-update` or `noUpdate`. It just a param at the moment.

**Comment by mattcat10** [comment]
It'd be nice if this "feature" was implemented or taken out of the docs for the contentful-cli.

**Comment by ruderngespra** [comment]
Sadly, we will not implement this in the near future. It has been [taken out of the docs.](https://github.com/contentful/contentful-import/commit/2004ead7bec46be41700aaff9534bdc0a27adf05)
