### ISSUE TITLE
Data Import/Migration--how to keep original created dates while importing data from another space in contentful ?

### ISSUE THREAD

**Issue by kottek** [contentful/contentful-import#119]
We've noticed that when content is imported from the JSON file, the sys.createdAt date changes to when the migration happens.This is not an expected behaviour when data needs to be migrated between spaces.

Is there a workaround for this? 

@Khaledgarbaya I have seen a similar post couple of years back and you have assisted on this issue.Can you please help me in this ?

**Comment by Khaledgarbaya** [comment]
Hey @kottek,

Unfortunately, `sys.createdAt` is read-only it's set by the backend at creation and we can't change it. the only workaround I can see right now is to have user controlled field for the creation date

Cheers,
Khaled

**Comment by ruderngespra** [comment]
Closing this issue for now since it's open for a long time with no reaction.
