### ISSUE TITLE
Bad Request - Message: Previously published fields are invalid

### ISSUE THREAD

**Issue by studentofcoding** [contentful/contentful-import#125]
Hey Contentful, so i'm in the process of importing the content-file for my site, and the 400 Bad Request showed

┌──────────────────────────────────────────────────┐
│ The following entities are going to be imported: │
├─────────────────────────────────┬────────────────┤
│ Content Types                   │ 2              │
├─────────────────────────────────┼────────────────┤
│ Editor Interfaces               │ 2              │
├─────────────────────────────────┼────────────────┤
│ Locales                         │ 1              │
├─────────────────────────────────┼────────────────┤
│ Entries                         │ 0              │
├─────────────────────────────────┼────────────────┤
│ Assets                          │ 0              │
├─────────────────────────────────┼────────────────┤
│ Webhooks                        │ 0              │
└─────────────────────────────────┴────────────────┘
 √ Validating content-file
 √ Initialize client (1s)
 √ Checking if destination space already has any content and retrieving it (2s)
 √ Apply transformations to source data (1s)
 √ Push content to destination space
   √ Connecting to space (1s)
   √ Importing Locales (1s)
   √ Importing Content Types (4s)
   √ Publishing Content Types (1s)
   √ Importing Editor Interfaces (2s)
   √ Importing Assets (4s)
   √ Publishing Assets (0s)
   √ Archiving Assets (1s)
   √ Importing Content Entries (4s)
   √ Publishing Content Entries (1s)
   √ Archiving Entries (0s)
   √ Creating Web Hooks (1s)
Finished importing all data
┌───────────────────────┐
│ Imported entities     │
├───────────────────┬───┤
│ Locales           │ 1 │
├───────────────────┼───┤
│ Content Types     │ 1 │
├───────────────────┼───┤
│ Editor Interfaces │ 1 │
├───────────────────┼───┤
│ Assets            │ 0 │
├───────────────────┼───┤
│ Published Assets  │ 0 │
├───────────────────┼───┤
│ Archived Assets   │ 0 │
├───────────────────┼───┤
│ Entries           │ 0 │
├───────────────────┼───┤
│ Published Entries │ 0 │
├───────────────────┼───┤
│ Archived Entries  │ 0 │
├───────────────────┼───┤
│ Webhooks          │ 0 │
└───────────────────┴───┘
The import took a few seconds (15s)

[
  {
    "ts": "2019-09-26T07:33:36.072Z",
    "level": "error",
    "error": {
      "name": "BadRequest",
      "entity": {
        "sys": {
          "space": {
            "sys": {
              "type": "Link",
              "linkType": "Space",
              "id": "37jvonobvsvd"
            }
          },
          "id": "post",
          "type": "ContentType",
          "createdAt": "2019-08-13T17:52:50.755Z",
          "updatedAt": "2019-08-15T03:26:38.803Z",
          "environment": {
            "sys": {
              "id": "master",
              "type": "Link",
              "linkType": "Environment"
            }
          },
          "publishedVersion": 17,
          "publishedAt": "2019-08-15T03:26:38.803Z",
          "firstPublishedAt": "2019-08-13T17:52:51.153Z",
          "createdBy": {
            "sys": {
              "type": "Link",
              "linkType": "User",
              "id": "44HsEvWtTVjj31u9g6CZX4"
            }
          },
          "updatedBy": {
            "sys": {
              "type": "Link",
              "linkType": "User",
              "id": "44HsEvWtTVjj31u9g6CZX4"
            }
          },
          "publishedCounter": 9,
          "version": 18,
          "publishedBy": {
            "sys": {
              "type": "Link",
              "linkType": "User",
              "id": "44HsEvWtTVjj31u9g6CZX4"
            }
          }
        },
        "displayField": "title",
        "name": "Post",
        "description": "",
        "fields": [
          {
            "id": "secret",
            "name": "Secret",
            "type": "Boolean",
            "localized": false,
            "required": false,
            "validations": [
            ],
            "disabled": false,
            "omitted": false
          },
          {
            "id": "title",
            "name": "Title",
            "type": "Symbol",
            "localized": false,
            "required": true,
            "validations": [
              {
                "unique": true
              }
            ],
            "disabled": false,
            "omitted": false
          },
          {
            "id": "slug",
            "name": "Slug",
            "type": "Symbol",
            "localized": false,
            "required": true,
            "validations": [
              {
                "unique": true
              }
            ],
            "disabled": false,
            "omitted": false
          },
          {
            "id": "author",
            "name": "Author",
            "type": "Array",
            "localized": false,
            "required": true,
            "validations": [
            ],
            "disabled": false,
            "omitted": false,
            "items": {
              "type": "Link",
              "validations": [
                {
                  "linkContentType": [
                    "author"
                  ]
                }
              ],
              "linkType": "Entry"
            }
          },
          {
            "id": "date",
            "name": "Date",
            "type": "Date",
            "localized": false,
            "required": false,
            "validations": [
            ],
            "disabled": false,
            "omitted": false
          },
          {
            "id": "hero",
            "name": "Hero",
            "type": "Link",
            "localized": false,
            "required": true,
            "validations": [
              {
                "linkMimetypeGroup": [
                  "image"
                ]
              }
            ],
            "disabled": false,
            "omitted": false,
            "linkType": "Asset"
          },
          {
            "id": "excerpt",
            "name": "Excerpt",
            "type": "Symbol",
            "localized": false,
            "required": true,
            "validations": [
              {
                "size": {
                  "min": 1,
                  "max": 200
                },
                "message": "Excerpts are cut at 140 characters"
              }
            ],
            "disabled": false,
            "omitted": false
          },
          {
            "id": "body",
            "name": "Body",
            "type": "Text",
            "localized": false,
            "required": true,
            "validations": [
            ],
            "disabled": false,
            "omitted": false
          }
        ]
      },
      "data": {
        "status": 400,
        "statusText": "Bad Request",
        "message": "Previously published fields are invalid",
        "details": {
        },
        "request": {
          "url": "https://api.contentful.com:443/spaces/5i9wri0f348f/environments/master/content_types/post",
          "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/vnd.contentful.management.v1+json",
            "X-Contentful-User-Agent": "app contentful.cli/1.1.0; feature space-import; sdk contentful-management.js/5.2.1; platform node.js/v10.16.3; os Windows/10.0.17763;",
            "Authorization": "Bearer ...hlrD8",
            "user-agent": "node.js/v10.16.3",
            "Accept-Encoding": "gzip",
            "X-Contentful-Version": 2,
            "Content-Length": 1347
          },
          "method": "put",
          "payloadData": "{\"displayField\":\"title\",\"name\":\"Post\",\"description\":\"\",\"fields\":[{\"id\":\"secret\",\"name\":\"Secret\",\"type\":\"Boolean\",\"localized\":false,\"required\":false,\"validations\":[],\"disabled\":false,\"omitted\":false},{\"id\":\"title\",\"name\":\"Title\",\"type\":\"Symbol\",\"localized\":false,\"required\":true,\"validations\":[{\"unique\":true}],\"disabled\":false,\"omitted\":false},{\"id\":\"slug\",\"name\":\"Slug\",\"type\":\"Symbol\",\"localized\":false,\"required\":true,\"validations\":[{\"unique\":true}],\"disabled\":false,\"omitted\":false},{\"id\":\"author\",\"name\":\"Author\",\"type\":\"Array\",\"localized\":false,\"required\":true,\"validations\":[],\"disabled\":false,\"omitted\":false,\"items\":{\"type\":\"Link\",\"validations\":[{\"linkContentType\":[\"author\"]}],\"linkType\":\"Entry\"}},{\"id\":\"date\",\"name\":\"Date\",\"type\":\"Date\",\"localized\":false,\"required\":false,\"validations\":[],\"disabled\":false,\"omitted\":false},{\"id\":\"hero\",\"name\":\"Hero\",\"type\":\"Link\",\"localized\":false,\"required\":true,\"validations\":[{\"linkMimetypeGroup\":[\"image\"]}],\"disabled\":false,\"omitted\":false,\"linkType\":\"Asset\"},{\"id\":\"excerpt\",\"name\":\"Excerpt\",\"type\":\"Symbol\",\"localized\":false,\"required\":true,\"validations\":[{\"size\":{\"min\":1,\"max\":200},\"message\":\"Excerpts are cut at 140 characters\"}],\"disabled\":false,\"omitted\":false},{\"id\":\"body\",\"name\":\"Body\",\"type\":\"Text\",\"localized\":false,\"required\":true,\"validations\":[],\"disabled\":false,\"omitted\":false}]}"
        },
        "requestId": "88dbca601d0363b3a5dec6fb6334ed31"
      }
    }
  }
]

What should i do to fix it? 
For the detailed system about the project, i use a Gatsby starter, with Windows 10 System (i don't change anything related to the source file).

Thanks

**Comment by jroehl** [comment]
Hi @studentofcoding,
did you try the import before? Is the space you're trying to import the data into empty?

**Comment by ruderngespra** [comment]
Closing this issue for now since it's open for a long time with no reaction.

**Comment by douglasg14b** [comment]
The error could include helpful information, unfortunately it does not...
