### ISSUE TITLE
Data migration - keeping original created dates

### ISSUE THREAD

**Issue by temelj** [contentful/contentful-import#16]
We've noticed that when content is imported the sys.createdAt date change to when the migration happens.
This is not a desired effect if data needs to be migrated between spaces.

Is there a workaround for this? Or does the system lock down the ability to specify a createdAt date string?

**Comment by Khaledgarbaya** [comment]
Hi @temelj,
 current there is no way to change the createdAt using the API. I would suggest you have seperate fields for dates if you want to have more control over that.

Best,
Khaled

**Comment by temelj** [comment]
Hi Khaled,

the existing data is in a production environment that needs to be migrated to a new space.
The new space will have some minor changes applied to the content types as per new specifications.

In the current production environment we retrieve entries by a given content type in order: "-sys.createdAt".

We would like to maintain the logic without introducing a new field (ie. "publishedAt").
The reason against using a "publishedAt" field is that currently contentful does not allow any functions to be executed when an entry is published. In our instance, it would be a function that would set the "publishedAt" field to a current date.  

If this field is set as "Required", then the content editors will have to set a published date every time they create a new entry.  Using sys.createdAt ensured a consistent, valid and "user-input" error proof way of ensuring the chronological order of entries.

But I do understand that the sys.createdAt or any sys.* data cannot and should not be changed.

### Possible Solution
Therefore, as for your suggestion to create a separate field, we could attempt the following:
Create a new "publishedAt" field that is disabled for content editors.
And after importing, we'd have to write a custom management script that would take the original exported json data (containing the original createdAt dates) and then update this publishedAt field.

Our front-end can then display the publishedAt if it is set, otherwise revert to sys.createAt.

### The Problem
Contentful-Export will generate a json document containing content_type and entries.
The entries in the exported json document are in chronological order. sys.createdAt Ascending.
(PS: I confirmed this by loading json in a datatable and it was a visual check)

Now when contentful-import is called, I understand that the exported json is piped through and entries are re-created in an asynchronous manner.

Therefore the resulting data may not be re-created in the same order as in the export.

Is there a way to ensure that the data in the new space is created in a chronological order (by sys.createdAt)?  

Could I use these undocumented usage parameters?

  .option('rate-limit', {
    describe: 'How many requests to perform per period of time, default is 5',
    type: 'number',
    default: 5
  })
  .option('rate-limit-period', {
    describe: 'How much time to wait before retry in ms, default 1000',
    type: 'number',
    default: 1000
  })

Set the rate-limit to 1?  

I hope that I didn't complicate my explanation too much.  Thanks for your input in advance.

**Comment by Khaledgarbaya** [comment]
Hi @temelj,

The order is not guaranteed because of the JSON parsing, what you can do is use the contentful-import as a [library](https://github.com/contentful/contentful-import#usage-as-a-library) and apply some transformation to the JSON before feeding it to the contentful-import. We are working on having some transformation callbacks when importing like [here](https://github.com/contentful/contentful-batch-libs/blob/master/lib/transform/transform-space.js#L14) but this is still highly experimental. You can even use the [content-batch-libs](https://github.com/contentful/contentful-batch-libs)'s `push-to-space` method.
I apologize for the complex workflow, but this will change soon as we are very busy trying to make the tool more stable before adding more features.
If need any help feel free to open an issue anytime and I'll do my best to help.

Best,
Khaled

**Comment by temelj** [comment]
I'm what way do you propose to do transformations to the json?

**Comment by Khaledgarbaya** [comment]
You can put the dates you want in the `publishAt` field for example or sort the entries by `createdAt`

**Comment by temelj** [comment]
I've considered that.  The population of publishedAt is not a problem.

And I've confirmed that in the exported json (from original space) the data is indeed in chronological order. 

The import doesn't import it on that order.  I am not sure what happens to the json in the import operation.  I'm assuming that entries are bunched and sent to the apis for creation

**Comment by Khaledgarbaya** [comment]
I am closing this issue for now, feel free to create a new one if needed
