### ISSUE TITLE
What goes inside data To import.json

### ISSUE THREAD

**Issue by arhoy** [contentful/contentful-import#193]
The documentation states the json file should look like this
```
{
  "contentTypes": [],
  "entries": [],
  "assets": [],
  "locales": [],
  "webhooks": [],
  "roles": [],
  "editorInterfaces": []
}
```

What is an example contentType and entry ?
I have tried to use my contentType name I created, ie the content model name and the entries as a json. 

But I get error
```
  name: 'ContentfulMultiError',
  errors: [
    { ts: '2020-04-23T06:18:59.943Z', level: 'error', error: [Error] }
  ]
```
Can someone please show me example?
Thank you

I am trying to import a bunch of entries into an already existing content type with images.

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
