### ISSUE TITLE
Missing items field in contentTypeSchema's fields

### ISSUE THREAD

**Issue by dpinol** [contentful/contentful-import#262]
Hi,
I tried to use the joi schema at dist/utils/schema.js to validate a json export, but it fails because contentTypeSchema misses the "items" entry for models of type Array.
So joi.validate fails with 
`Error: child "contentTypes" fails because ["contentTypes" at position 0 fails because [child "fields" fails because ["fields" at position 2 fails because ["items" is not allowed]]]]
`
Example:
```
"fields": [
        {
          "id": "elements",
          "name": "Elements",
          "type": "Array",
          "localized": false,
          "required": true,
          "disabled": false,
          "omitted": false,
          "items": {
            "type": "Link",
            "validations": [
              {
                "linkContentType": [
                  "element"
                ]
              }
            ],
            "linkType": "Entry"
          }
        },
       
```

I guess adding   
`sys: _joi2.default.object(),
`
to contentTypeSchema might solve the issue

The same happens with assets & editorInterfaces:

> Error: child "assets" fails because ["assets" at position 0 fails because [child "fields" fails because ["title" is not allowed, "description" is not allowed]]]
> Error: child "editorInterfaces" fails because ["editorInterfaces" at position 0 fails because [child "controls" fails because ["controls" at position 0 fails because ["widgetNamespace" is not allowed]]]]
> 

thanks

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
