### ISSUE TITLE
Rate Limiting 

### ISSUE THREAD

**Issue by matt-lavinia** [contentful/contentful-import#31]
Ran an import this morning and am consistently getting an "Infinity" time window for the assets to create.

`Rate limit error occured. Waiting for Infinity ms before retrying....
Rate limit error occured. Waiting for Infinity ms before retrying....
Rate limit error occured. Waiting for Infinity ms before retrying....
Rate limit error occured. Waiting for Infinity ms before retrying....
Rate limit error occured. Waiting for Infinity ms before retrying....
Rate limit error occured. Waiting for Infinity ms before retrying....
Rate limit error occured. Waiting for Infinity ms before retrying....
Rate limit error occured. Waiting for Infinity ms before retrying....
Rate limit error occured. Waiting for Infinity ms before retrying....
Rate limit error occured. Waiting for Infinity ms before retrying....
Rate limit error occured. Waiting for Infinity ms before retrying....
Rate limit error occured. Waiting for Infinity ms before retrying....
Rate limit error occured. Waiting for Infinity ms before retrying....
Rate limit error occured. Waiting for Infinity ms before retrying....
Rate limit error occured. Waiting for Infinity ms before retrying....
Rate limit error occured. Waiting for Infinity ms before retrying....
Rate limit error occured. Waiting for Infinity ms before retrying....
Rate limit error occured. Waiting for Infinity ms before retrying....`

Is there anything we can do to avoid this? 
The knock-on affect of this is this rate limiting is organization wide, so if we have a sync job running mid-day and it caps our rate limit - our production content teams are unable to work in the admin. Seems to be less a import issue, more of a rate limiting across the CMA in general, but this tool can consistently break the Admin UI for our organization. :)

**Comment by axe312ger** [comment]
This is a known bug from an older version. Can you please upgrading your `contentful-import` module?

Please let me know if this solves your issue :)

**Comment by matt-lavinia** [comment]
Verified running v4.1.0 - re-running today and will add further details if needed.
![image](https://cloud.githubusercontent.com/assets/742861/24731583/15396bfa-1a39-11e7-999d-2be0982498ca.png)

**Comment by matt-lavinia** [comment]
I'm seeing the warnings regarding Node v and will try a couple of things with Node version updates.

**Comment by axe312ger** [comment]
@matt-lavinia alright. Upgrading to 4.7 (or 4.8.2) shouldn't cause that big problems. Good luck! :)
