### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by isaachinman** [contentful/contentful-import#324]
Hi there, it seems like this package is actively maintained, but I was surprised to find that not only are there no types exported from `contentful-import`, there also aren't any at `@types/contentful-import`.

Does Contentful intend to support TS users?

**Comment by emilsbee** [comment]
I'm also interested about typescript support for this package. It still seems to be actively maintained, are there any plans for it?

**Comment by ruderngespra** [comment]
hey, hey, with [the latest release](https://github.com/contentful/contentful-import/pull/908) we now do provide a public ts interface for the module. Please feel free to re-open this if you are missing any features or running into issues.
