### ISSUE TITLE
entry counts from source to destination

### ISSUE THREAD

**Issue by temelj** [contentful/contentful-import#36]
I am not getting the same counts from source space entries to destination space entries.

If I view the entries via the contentful.com website, I get 250 total entries out of which 20 are draft.

So if I export this, i'd expect my destination space to have 230 entries?

I'm getting 128.
The contentful-import tool stated that it imported 230.

**Comment by axe312ger** [comment]
So the web app tells you it got only 128 entries while the import tool told you that it imported 230?

Are you sure there are no filters active in the web app?

You might file an issue here, so we can have a look at your data/try it on our own: https://support.contentful.com/hc/en-us/requests/new

**Comment by temelj** [comment]
Yes, you are correct.  I've updated the tooling re-ran the import and its not quite right again.

I can confirm that I'm using the latest version (which includes the contentful-batch-libs v5.6.2)

The contentful-import took 35 minutes.
Content Types 11
Editor Interfaces 9
Entries 230
Assets 1359
Locales 1
Webhooks 0
Roles 3

Assets are fine with a count of 1359.
Entries is reported to be 230, however I only see 144 entries in the contentful.com for the space.

**Comment by temelj** [comment]
I have had some success:

I edited the exported JSON document, cleared the `assets: [], ` and re-executed the contetnful-import command.

It managed to import all 230 entries correctly. However in terms of the DRAFT entries count, I've only got 4 in the destination whereas the source has 20 draft entries.

**Comment by axe312ger** [comment]
I guess no errors where displayed?

Also, can you please do me a favour and check if the draft entries you are talking about appear in the exported JSON file?

I want to find out if the problem exists on the export side or import side of the tool chain.

**Comment by temelj** [comment]
To make explanation a bit easier, i'll name the original environment where the data is being exported from: PROD and the destination space STAGING.

From the contentful.com website, in PROD I have 250 entries (if i view All)
This includes:
230 published entries
20 draft entries
8 archived entries

calling contentful-export on the PROD data, I get 230 entries in TOTAL. My assumption is that only the published entries are exported.

From the contentful.com website, in STAGING I have 220 entries (if I view All)
This includes:
216 published entries
4 draft entries
0 archived entries

calling contentful-export on the STAGING data, I get 216 entries in TOTAL. Again my assumption is that only the published entries are exported.


Analysing the draft entries in the STAGING space, I found that 
**1 had a missing or inaccessible image (linked to a media asset item).**
in PROD, this entry is flagged as published, however the media is also missing. (user must have deleted the asset item)
**2 with a missing reference to another entry id.**
in PROD, this missing entry is actually set to draft, hence why the export didn't include it. (again, this was done by the user)
**1 with a missing reference to another entry id.**
in PROD, this missing entry is actually set to archived

So, the 4 that are in DRAFT status in STAGING is understandable and explainable.
**I am still missing 10.**

Would you like the exported JSON files? Would that help?

**Comment by axe312ger** [comment]
@temelj yeah, actually I would love to have a look since we did not come across this in our internal tests (We do more that what you can see here in the CI)

But our test Space data is way more fresh than what you might have in there since we are generating this data which excludes weird stuff humans might bring in.

Please do not share your data here in Github, open a ticket here: https://support.contentful.com/hc/en-us/requests/new, add this issue url and attach your json files. That should be enough that the tickets gets assigned to me.

You may also share your Space id's and an access token, so I can have a look directly, maybe even try with my machine to export and import and see whats happening there.

All the best,
Benedikt

**Comment by temelj** [comment]
Hi Benedikt,

I have created a support ticket and attached the exported PROD data.

However, I have noticed another discrepancy between the export data.

I have 2 entries that have previously been published where one references the other.
The referenced entry has been set to draft. It appears that because the parent entry references a draft entry (as of now), the contentful-export no longer includes the (published) parent or the (draft) referenced entry. 
**Is this expected behaviour?**

For us, this is undesirable as we're losing information as part of the migration export.

PS: As for the filters - I don't actually know what they are - we are not using any filters.

Kind Regards,
Ado

**Comment by temelj** [comment]
Hi,

I've had some luck importing the production data to a staging space including all assets, entries and so on.
Meaning that the counts add up.

However, I have noticed that executing the contentful-import and contentful-export version cannot be controlled by "npm install -g <package>@version' because every time you get a particular version, the batch-libs actually get the latest. Which at the time of writing is at v5.7.0 and I've been targeting anything between v5.6.2 and v5.7.0 and that is due to the nature of the package.json reference of batch-libs with "^5.7.0"  or previously "^5.6.2".  That means that any "minor" change you publish, calling npm install -g <package> will get the latest of the batch-libs.

This makes it very difficult to diagnose what went wrong with the previous export/import attempts.

I will do a few more migration runs over the weekend to test.

But I am getting a strange error showing up in the logs: When I execute contentful-import i get the following error show up but it proceeds then without issues:
```
contentful-import : info import Contentful Import Tool
At line:1 char:1
+ contentful-import --space-id fnvj7cztdncd --management-token fe673ed4 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (info import Contentful Import Tool:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
info
 import
 Importing data ...
```

**Comment by temelj** [comment]
Is it expected behaviour if i use the `--include-drafts` option in the contentful-export to get archived entries from the source space over to the destination space (in draft)?

That is what I'm seeing in my tests.

**Comment by axe312ger** [comment]
Does this still happen to you @temelj? Should be fixed since quite some time :)
