### ISSUE TITLE
Better error reporting when passing wrongful data

### ISSUE THREAD

**Issue by tomasdev** [contentful/contentful-import#38]
`ERR! TypeError: expecting an array or an iterable object but got [object Null] `

Related to #6. It is cumbersome to debug when passing the incorrect data (in any user case other than trying to import something else than a exact export from another space) and we get this error. Ideally, it would at least say trying which property it failed.

Thoughts?

**Comment by Khaledgarbaya** [comment]
Hi @tomasdev ,
You are right, this is on our list definitely.
Best,
Khaled

**Comment by tomasdev** [comment]
@Khaledgarbaya what would be the best way of debugging where it is breaking currently? I'm looking at https://github.com/contentful/contentful-import/blob/master/lib/index.js

**Comment by tomasdev** [comment]
Update: `contentTypes` and `roles` seem to be mandatory when importing content.

**Comment by axe312ger** [comment]
Hey @tomasdev,

thanks for investigating further, as Khaled mentioned, that is on our list and we will come to proper error reporting and more as soon as possible.

I will keep you updated in this issue when sth happends,
all the best,
Benedikt

**Comment by tomasdev** [comment]
Perhaps check around "Finished importing all data" if `response` is an empty array and it's not supposed to be (i.e. original entries array isn't) throw an error instead of saying it all went okay?

**Comment by tomasdev** [comment]
Found out:
- "Validation error"s coming back from the API are not coming back into `createEntryInDestination` or `createInDestination` of `creation.js` in `contentful-batch-libs`
- Probably a bug around the way `handleEntryCreationErrors` works

`(node:18133) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): InvalidEntry: {`

**Comment by axe312ger** [comment]
@tomasdev we are on it -> https://github.com/contentful/contentful-import/pull/58

**Comment by tomasdev** [comment]
@axe312ger i'll check it out and let you know if it throws on ValidationErrors
