### ISSUE TITLE
Background color of info messages on Windows

### ISSUE THREAD

**Issue by Roblinde** [contentful/contentful-import#44]
With the standard background of PowerShell in windows you can't really read the info messages: 

![image](https://cloud.githubusercontent.com/assets/1835323/26248396/81cfbed2-3ca2-11e7-9a7a-c5e6eb2d80e8.png)

**Comment by axe312ger** [comment]
Related to #37 or should at least be fixed together with it :)

**Comment by axe312ger** [comment]
will be fixed via #58

**Comment by axe312ger** [comment]
Fixed in latest major :)
