### ISSUE TITLE
Importer exceeds rate limit for organization

### ISSUE THREAD

**Issue by willalbone** [contentful/contentful-import#45]
The importer does not cope well when importing a large number of entries and exhausts the rate limit available for the associated organization with retry wait times stretching from around 1000ms to 900000+ms. This then blocks all read requests to other spaces within the same organization. The importer should account for this and throttle it's requests so as not to exceed Contentful's rate limit.

**Comment by Khaledgarbaya** [comment]
Hi @willalbone, which version of the contentful-import are you using?

**Comment by willalbone** [comment]
4.4.2

**Comment by Khaledgarbaya** [comment]
The tool is using the SDK underneath, and rate limiting is handled there. but the number looks a bit weird. I'll look into it asap, thanks for reporting.

**Comment by willalbone** [comment]
Taking a look through the code my guess would be this is originating in contentful-batch-libs/lib/creation/createEntries as it is calling Bluebird's Promise.map with infinite concurrency compared to other Promise.map calls which are specifying concurrency of between 4 and 6

**Comment by Khaledgarbaya** [comment]
Oh yeah, you are right it is [here](https://github.com/contentful/contentful-batch-libs/blob/master/lib/push/creation.js#L30). I will push a fix today.

**Comment by Khaledgarbaya** [comment]
@willalbone this [PR](https://github.com/contentful/contentful-batch-libs/pull/116) should fix it. I'll try to get it merged today

**Comment by Khaledgarbaya** [comment]
this is now fixed in https://github.com/contentful/contentful-import/pull/46

**Comment by willalbone** [comment]
Perfect, thanks!
