### ISSUE TITLE
(0 , _partialRight.partialRight) is not a function when importing to empty space

### ISSUE THREAD

**Issue by svdbrg** [contentful/contentful-import#47]
Hi all!

I've managed to do an export of one space and now trying to import that data to a completely new space. I am however running into a problem (see error below).

I'm running the latest (v 4.4.3) version of contentful-import straight from the command line.

Any thoughts or clues as to how to solve this or what might be missing?

`contentful-import --space-id [spaceid] --management-token [token] --content-file "contentful-export-1495556235477.json"

info import Contentful Import Tool
info import Importing data ...
info Checking if destination space already has any content and retrieving it
ERR! import TypeError: (0 , _partialRight.partialRight) is not a function
ERR! import     at C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\contentful-batch-libs\dist\transform\transform-space.js:17:56
ERR! import     at tryCatcher (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\util.js:16:23)
ERR! import     at Object.gotValue (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\reduce.js:157:18)
ERR! import     at Object.gotAccum (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\reduce.js:144:25)
ERR! import     at Object.tryCatcher (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\util.js:16:23)
ERR! import     at Promise._settlePromiseFromHandler (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:512:31)
ERR! import     at Promise._settlePromise (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:569:18)
ERR! import     at Promise._settlePromiseCtx (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:606:10)
ERR! import     at Async._drainQueue (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\async.js:138:12)
ERR! import     at Async._drainQueues (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\async.js:143:10)
ERR! import     at Immediate.Async.drainQueues (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\async.js:17:14)
ERR! import     at runCallback (timers.js:651:20)
ERR! import     at tryOnImmediate (timers.js:624:5)
ERR! import     at processImmediate [as _immediateCallback] (timers.js:596:5)
ERR! import  TypeError: (0 , _partialRight.partialRight) is not a function
ERR! import     at C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\contentful-batch-libs\dist\transform\transform-space.js:17:56
ERR! import     at tryCatcher (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\util.js:16:23)
ERR! import     at Object.gotValue (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\reduce.js:157:18)
ERR! import     at Object.gotAccum (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\reduce.js:144:25)
ERR! import     at Object.tryCatcher (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\util.js:16:23)
ERR! import     at Promise._settlePromiseFromHandler (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:512:31)
ERR! import     at Promise._settlePromise (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:569:18)
ERR! import     at Promise._settlePromiseCtx (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:606:10)
ERR! import     at Async._drainQueue (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\async.js:138:12)
ERR! import     at Async._drainQueues (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\async.js:143:10)
ERR! import     at Immediate.Async.drainQueues (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\async.js:17:14)
ERR! import     at runCallback (timers.js:651:20)
ERR! import     at tryOnImmediate (timers.js:624:5)
ERR! import     at processImmediate [as _immediateCallback] (timers.js:596:5)
ERR! import TypeError: (0 , _partialRight.partialRight) is not a function
ERR! import     at C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\contentful-batch-libs\dist\transform\transform-space.js:17:56
ERR! import     at tryCatcher (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\util.js:16:23)
ERR! import     at Object.gotValue (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\reduce.js:157:18)
ERR! import     at Object.gotAccum (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\reduce.js:144:25)
ERR! import     at Object.tryCatcher (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\util.js:16:23)
ERR! import     at Promise._settlePromiseFromHandler (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:512:31)
ERR! import     at Promise._settlePromise (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:569:18)
ERR! import     at Promise._settlePromiseCtx (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:606:10)
ERR! import     at Async._drainQueue (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\async.js:138:12)
ERR! import     at Async._drainQueues (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\async.js:143:10)
ERR! import     at Immediate.Async.drainQueues (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\async.js:17:14)
ERR! import     at runCallback (timers.js:651:20)
ERR! import     at tryOnImmediate (timers.js:624:5)
ERR! import     at processImmediate [as _immediateCallback] (timers.js:596:5)
ERR! import  Failed within
ERR! import  TypeError: (0 , _partialRight.partialRight) is not a function
ERR! import     at C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\contentful-batch-libs\dist\transform\transform-space.js:17:56
ERR! import     at tryCatcher (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\util.js:16:23)
ERR! import     at Object.gotValue (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\reduce.js:157:18)
ERR! import     at Object.gotAccum (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\reduce.js:144:25)
ERR! import     at Object.tryCatcher (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\util.js:16:23)
ERR! import     at Promise._settlePromiseFromHandler (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:512:31)
ERR! import     at Promise._settlePromise (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:569:18)
ERR! import     at Promise._settlePromiseCtx (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:606:10)
ERR! import     at Async._drainQueue (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\async.js:138:12)
ERR! import     at Async._drainQueues (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\async.js:143:10)
ERR! import     at Immediate.Async.drainQueues (C:\Users\svdbr\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\async.js:17:14)
ERR! import     at runCallback (timers.js:651:20)
ERR! import     at tryOnImmediate (timers.js:624:5)
ERR! import     at processImmediate [as _immediateCallback] (timers.js:596:5)`

**Comment by Khaledgarbaya** [comment]
Hi @svdbrg ,
I just released a fix in the batch-libs in few minutes a new patch should be released.
If you update contentful-import in few minutes you should get it

**Comment by Khaledgarbaya** [comment]
This should now be fixed

**Comment by svdbrg** [comment]
That was VERY fast! Works great now. Many thanks!
