### ISSUE TITLE
Guidance on "update" parameter in import config

### ISSUE THREAD

**Issue by tbuckham** [contentful/contentful-import#504]
Hi there - I have unsuccessfully tried to find what  "update": false achieves in the config.json file when running an import - if set to false does it simply ignore any existing content with the same IDs and make no change to them? I was hoping to avoid some tests to deduce this and just go with documented guidelines, but couldn't find anything.

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
