### ISSUE TITLE
 contentfull import Checking if destination space already 

### ISSUE THREAD

**Issue by buzzyluxecom** [contentful/contentful-import#521]
NotFound: Status: 404 - Not Found - Message: The resource could not be found. - Request ID: 7e1ccd7277d4422710d6c

-------------------------------------------------

[
  {
    "ts": "2021-09-07T15:30:22.725Z",
    "level": "error",
    "error": {
      "originalError": {
        "name": "NotFound",
        "message": "{\n  \"status\": 404,\n  \"statusText\": \"Not Found\",\n  \"message\": \"The resource could not be found.\",\n  \"details\": {},\n  \"request\": {\n    \"url\": \"/spaces/j4vm0d728rwo\",\n    \"headers\": {\n      \"Accept\": \"application/json, text/plain, */*\",\n      \"Content-Type\": \"application/vnd.contentful.management.v1+json\",\n      \"X-Contentful-User-Agent\": \"app contentful.cli/1.9.0; feature space-import; sdk contentful-management.js/7.33.0; platform node.js/v14.17.5; os Windows/10.0.19042;\",\n      \"Authorization\": \"Bearer ...MTfGk\",\n      \"user-agent\": \"node.js/v14.17.5\",\n      \"Accept-Encoding\": \"gzip\"\n    },\n    \"method\": \"get\"\n  },\n  \"requestId\": \"c0f1c644f3d7f92009906c6b7e05b52a\"\n}"
      },
      "data": {
        "status": 404,
        "statusText": "Not Found",
        "message": "The resource could not be found.",
        "details": {
        },
        "request": {
          "url": "/spaces/j4vm0d728rwo",
          "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/vnd.contentful.management.v1+json",
            "X-Contentful-User-Agent": "app contentful.cli/1.9.0; feature space-import; sdk contentful-management.js/7.33.0; platform node.js/v14.17.5; os Windows/10.0.19042;",
            "Authorization": "Bearer ...MTfGk",
            "user-agent": "node.js/v14.17.5",
            "Accept-Encoding": "gzip"
          },
          "method": "get"
        },
        "requestId": "c0f1c644f3d7f92009906c6b7e05b52a"
      }
    }
  }
]

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
