### ISSUE TITLE
Status : 422  Unprocessable Entity

### ISSUE THREAD

**Issue by haidarally** [contentful/contentful-import#598]
Getting these Error on some entries, when importing an environment.

03:30:55 - InvalidEntry: Status: 422 - Unprocessable Entity - Message: Validation error - Details: The property "articleContents" is required here - Request ID: 0fef3301-c0d6-4817-8786-557a0ad4ecfe

13:27:36 - ValidationFailed: Status: 422 - Unprocessable Entity - Message: Validation error - Details: The asset has no files - Request ID: 6c3aee12-0a92-4e97-bb70-88e00341d652

13:31:96 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 822d3bd8-6d16-4f35-a5ba-d712c8ec1357

Any idea why?

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
