### ISSUE TITLE
Different import results with same exported file

### ISSUE THREAD

**Issue by stefanjudis** [contentful/contentful-import#7]
I'm running a fairly small import using a json file that I generated using contentful-export.
File to import 👉  https://gist.github.com/stefanjudis/3f5b9773304b2c750ec631f0811ffcde

Sometimes this is resulting in different results (look at the publishing state).

I'm on node `v7.2.0`.

```
> node --version
v7.2.0
```

I'm using the current version `v2.1.1`.

```
> contentful-import --version
2.1.1
```

## Run 1:

<img width="1156" alt="bildschirmfoto 2016-12-12 um 16 50 05" src="https://cloud.githubusercontent.com/assets/962099/21105675/6224fb62-c08b-11e6-95eb-178b01142008.png">

Output:

```
> contentful-import --space-id 0h1md4v1zmlu --management-token xxx --content-file ./car-demo/exports/export.json
info Contentful Import Tool: 
Importing data... 
info Checking if destination space already has any content and retrieving it 
info Pushing content to destination space 
info Updated Locale U.S. English 
info Created ContentType Car 
info Created ContentType LandingPage 
info Created ContentType Campaign 
info Published ContentType Campaign 
info Published ContentType Car 
info Published ContentType LandingPage 
info Created Asset 3D24Dj69NSQkwkI8OwsqK8 
info Created Asset kDYwhS2Tp62M2IgIAc24u 
info Processing Asset 3D24Dj69NSQkwkI8OwsqK8 
info Processing Asset kDYwhS2Tp62M2IgIAc24u 
info Published Asset 3D24Dj69NSQkwkI8OwsqK8 
info Published Asset kDYwhS2Tp62M2IgIAc24u 
info Created Entry 2EoARcS13Yqm8UwMsEU480 
info Created Entry 3euJsmdv60aEWecWO0cCKk 
info Created Entry 16BkP7YS304YGK8ece2SSg 
info Created Entry 3QxgcI14RGcakiiCoIqyMq 
info Published Entry 3euJsmdv60aEWecWO0cCKk 
info Published Entry 3QxgcI14RGcakiiCoIqyMq 
info Published Entry 16BkP7YS304YGK8ece2SSg 
info Successfully Imported all data 
``` 

## Run 2:

<img width="1150" alt="bildschirmfoto 2016-12-12 um 16 54 57" src="https://cloud.githubusercontent.com/assets/962099/21105768/bc471896-c08b-11e6-9b92-febd8138ab18.png">

Output:

```
> contentful-import --space-id 2bf7olvuceod --management-token xxx --content-file ./car-demo/exports/export.json
info Contentful Import Tool: 
Importing data... 
info Checking if destination space already has any content and retrieving it 
info Pushing content to destination space 
info Updated Locale U.S. English 
info Created ContentType Car 
info Created ContentType LandingPage 
info Created ContentType Campaign 
info Published ContentType Campaign 
info Published ContentType Car 
info Published ContentType LandingPage 
info Created Asset 3D24Dj69NSQkwkI8OwsqK8 
info Created Asset kDYwhS2Tp62M2IgIAc24u 
info Processing Asset 3D24Dj69NSQkwkI8OwsqK8 
info Processing Asset kDYwhS2Tp62M2IgIAc24u 
info Published Asset kDYwhS2Tp62M2IgIAc24u 
info Published Asset 3D24Dj69NSQkwkI8OwsqK8 
info Created Entry 3QxgcI14RGcakiiCoIqyMq 
info Created Entry 2EoARcS13Yqm8UwMsEU480 
info Created Entry 16BkP7YS304YGK8ece2SSg 
info Created Entry 3euJsmdv60aEWecWO0cCKk 
info Published Entry 2EoARcS13Yqm8UwMsEU480 
info Published Entry 3euJsmdv60aEWecWO0cCKk 
info Published Entry 3QxgcI14RGcakiiCoIqyMq 
info Published Entry 16BkP7YS304YGK8ece2SSg 
info Successfully Imported all data 
```

**Comment by Khaledgarbaya** [comment]
Thanks for reporting I will take a look asap

**Comment by axe312ger** [comment]
@stefanjudis does this still happen?

**Comment by stefanjudis** [comment]
Okay I just ran three imports that showed the same result. 
I'll close for now and 'll let you know if I come across this behavior again.

Thx. :)

**Comment by stefanjudis** [comment]
Okay, I'm running in the same behavior again.

I exported this file using `contentful-exporter`

https://gist.github.com/stefanjudis/4a122ff6d921920b0959b3f6fae866c1.

The import of this file lead to only one published entry.

![screen shot 2017-05-16 at 12 11 55](https://cloud.githubusercontent.com/assets/962099/26101289/e18fd934-3a30-11e7-8047-9417cbe51ff2.png)

But I clearly exported 4 published entries and the exported json file includes `publishedAt` for all of the entries.

Hopes this helps. :)

**Comment by Khaledgarbaya** [comment]
@stefanjudis that's a normal behaviour, if you want the drafts to be included you need to specify `--include-drafts` when exporting.
Can you do a quick comparison between the imported entries and what's in the json file ?
all entries in the json should be imported correctly.

**Comment by stefanjudis** [comment]
The problem is that I exported following state 👇 

![screen shot 2017-05-16 at 13 45 59](https://cloud.githubusercontent.com/assets/962099/26104409/051082c0-3a3e-11e7-9aee-bfb939ac7738.png)

And ended up with the state described in https://github.com/contentful/contentful-import/issues/7#issuecomment-301737896.

**Comment by Khaledgarbaya** [comment]
can you share the space with @axe312ger, he can make some tests

**Comment by axe312ger** [comment]
This is fixed via multiple fallbacks now in multiple releases in the past.
