### ISSUE TITLE
Potential issue in push-to-space.js file

### ISSUE THREAD

**Issue by christineywang** [contentful/contentful-import#74]
Hello,

A few users have come across an issue with the import tool. A possible error could look like this:
```TypeError: Cannot read property 'sys' of undefined```

The resolution seems to come with modifying the ```push-to-space.js``` file in the node_modules package.

Example path to the file in question:
```/Users/christinewang/.npm/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/dist/push/push-to-space.js```

The import error is resolved when the user changes two lines in the ```push-to-space.js``` file 
to check if ```entity``` exists.

In line 326, instead of ```return entityIdsToArchive.includes(entity.sys.id);```, the import works when you change it to ```return entity && entityIdsToArchive.includes(entity.sys.id);```.

And in line 344, instead of ```return entityIdsToPublish.includes(entity.sys.id);```, the import works when you change it to ```return entity && entityIdsToPublish.includes(entity.sys.id);```.

**Comment by Khaledgarbaya** [comment]
Hi @christineywang,
Thanks for your input usually an entry should have a `sys` property.
I will look into the issue asap.
Best,
Khaled

**Comment by dustinaleksiuk** [comment]
I'm having a similar error, but in a different place. The line in the stack trace is when it attempts to access the sys field on the contentType. This is the stack trace from the log file:

```
"TypeError: Cannot read property 'sys' of undefined",
        "/Users/daleksiuk/dev/import-export/node_modules/contentful-batch-libs/dist/push/push-to-space.js:343:47",
        "Array.filter (<anonymous>)",
        "publishEntities (/Users/daleksiuk/dev/import-export/node_modules/contentful-batch-libs/dist/push/push-to-space.js:342:36)",
        "Task.task (/Users/daleksiuk/dev/import-export/node_modules/contentful-batch-libs/dist/push/push-to-space.js:229:14)",
        "Promise.resolve.then.then.skipped (/Users/daleksiuk/dev/import-export/node_modules/listr/lib/task.js:169:30)",
        "<anonymous>"
```

The chunk of code that fails is this:

```
return {
                v: space.getEditorInterfaceForContentType(contentType.sys.id).then(function (ctEditorInterface) {
                  ctEditorInterface.controls = editorInterface.controls;
                  return ctEditorInterface.update();
                })
};
```

**Comment by Khaledgarbaya** [comment]
Hi @dustinaleksiuk and @christineywang  can you link the new branch from the bat libs and test again, if it fixes your issue
https://github.com/contentful/contentful-batch-libs/pull/138

**Comment by christineywang** [comment]
@Khaledgarbaya this may still not be working since we are still seeing this issue with users. I will test today.
