### ISSUE TITLE
[help wanted] [question] Linking asset references to imported data

### ISSUE THREAD

**Issue by Nappstir** [contentful/contentful-import#82]
Hey guys, 

So I have added all my assets to `Contentful` and now I need to upload some 'Articles' that reference said assets. Now I currently know how to do this by applying the `asset id` to the json formated file like so: 

```
"fields": {
        "articleTitle": {
          "en-US": "Back To School: Taxes, Health Insurance & Dependents"
        },
        "slug": {
          "en-US": "back-school-taxes-health-insurance-dependents"
        },
        "author": {
          "en-US": {
            "sys": {
              "type": "Link",
              "linkType": "Entry",
              "id": "25TzbxtqU00ywOSOKOyACW"
            }
          }
        },
        "articleImage": {
          "en-US": {
            "sys": {
              "type": "Link",
              "linkType": "Asset",
              "id": "2N5C54I9huUYUI68mS0iGY"
            }
          }
        },
      }
    }
```

So I can see that I can do `"type": "Link", "linkType": "Asset", "id": "<IMAGE_ID>"`, but I'm wondering if I can do something other than `id` to reference the asset I want to connect to the article or whatever piece of content model I have.

**Comment by axe312ger** [comment]
Hey Travis,

sorry, but our links only support the pattern you are already using. Some more details might be found here: https://www.contentful.com/developers/docs/concepts/links/

Best,
Benedikt

**Comment by axe312ger** [comment]
As mentioned, Links resolve via the id of the linked entity. The API does not support other kind of links. Closing here.
