### ISSUE TITLE
content-model-only option is not really mentioned in the README

### ISSUE THREAD

**Issue by szimek** [contentful/contentful-import#9]
In the README file it's mentioned that:
```
--skip-locales  Skips locales. Must be used with content-model-only. Copies only content-types [boolean]
```
However, this `content-model-only` option is not mentioned in any other place as one of available options. Looks like it's actually an option of `contentful-batch-libs/push/push-to-space`, but it would be great to mention it in the README.

**Comment by Khaledgarbaya** [comment]
@szimek ,
sorry for the late response. I am aware of that and it will be added soom to the README
Best,
Khaled
